{
  "embeddings": [
    {
      "tensorName": "My tensor",
      "tensorShape": [
        519,
        128
      ],
      "tensorPath": "https://gist.githubusercontent.com/dy567/4059b6949eb51d2e226a15f030edcf65/raw/352b09aecf2be8f8e83172cd29f9295aed72fe42/feature_vecs.tsv",
      "metadataPath": "https://gist.githubusercontent.com/dy567/4059b6949eb51d2e226a15f030edcf65/raw/352b09aecf2be8f8e83172cd29f9295aed72fe42/feature_class.tsv",
      "sprite": {
        "imagePath": "https://gist.githubusercontent.com/dy567/4059b6949eb51d2e226a15f030edcf65/raw/352b09aecf2be8f8e83172cd29f9295aed72fe42/sprite.jpg",
        "singleImageDim": [
          25,
          25
        ]
      }
    }
  ]
}
