{
  "embeddings": [
    {
      "tensorName": "My tensor",
      "tensorShape": [
        220,
        128
      ],
      "tensorPath": "https://gist.githubusercontent.com/dy567/fd868caf2b78cc8b21779f08208488b0/raw/acbb97e0c26a46c16124741bf6ec5bba14282f25/1013_room1_feature_vecs.tsv",
      "metadataPath": "https://gist.githubusercontent.com/dy567/0d5872fe71b2179f7ee26eb156064ca5/raw/b546452889264b32a7c8739db316d9eef905628d/1013_room1_feature_class.tsv",
      "sprite": {
        "imagePath": "https://raw.githubusercontent.com/dy567/ToF_TSNE/master/sprite_1013_room1.jpg",
        "singleImageDim": [
          100,
          100
        ]
      }
    }
  ]
}
